### ISSUE TITLE
Site use agreement

### ISSUE THREAD

**Issue by lisa-rieck** [capital-chaplains/corpchaps.com#14]
Hi Matt. I just cleaned this page up a bit, but when I go to the Corpchaps.com GitHub site it says there's no GitHub page for the Site Use Agreement. So I'm wondering if I did something wrong? Thanks for your help!

**Comment by matt-cook** [comment]
Sorry about that. You did it correctly, I was in the process of updating a few of the URL's. Should be all fixed now: http://capital-chaplains.github.io/corpchaps.com/site-use-agreement/
