### ISSUE TITLE
Need smaller H2

### ISSUE THREAD

**Issue by sarahschilling** [capital-chaplains/corpchaps.com#16]
Matt,

I tried changing the h2 & h3 font-size with Atom & syncing it through GitHub, but none of my attempts (#content h2, #main #feat h2, and .title h2) appeared to actually change the h2s on the dev site (I was working on the Become a Corporate Chaplain page. I'm able to change colors, so I'm assuming there's some other place in the CSS where there's a default/master font size for headers, that I'm not seeing.

Could you please let me know where to make font size changes & I can play around with what size we'd like h2s and h3s, etc.?

Also, there is either a lot of margin below h2s or it's the line height for h2s. Either way, it would be great to cut it down by about half the pixels. I'd like to know where to make this change as well.

Sarah

**Comment by matt-cook** [comment]
Related to #18: CSS is currently pretty restrictive from the old layout. I'd like to finalize all of our needed design updates on Saturday so we can make a cohesive plan, and I'll take care of them all at once.

**Comment by matt-cook** [comment]
I'm adding a template page with all available formatting options (#33). Once that's complete we can review if you still need additional formats.

**Comment by matt-cook** [comment]
Do any of the formats here: http://capital-chaplains.github.io/corpchaps.com/template/ look like what you need? If not, feel free to re-open this issue.
