### ISSUE TITLE
How do I make select text a smaller font size?

### ISSUE THREAD

**Issue by lisa-rieck** [capital-chaplains/corpchaps.com#18]
I put in the HTML code in my markdown editor, and it looked like it worked, but after I saved and synced there was no change on the actual site.

**Comment by matt-cook** [comment]
Currently, for whatever reason the old site used very similar (or the same?) formatting for all the headers, and there are a few other CSS rules that seem a bit restrictive/funky now. I'd like to review all our suggested design/formatting changes on Saturday then take care of them all at once.

**Comment by matt-cook** [comment]
Let's review once #33 is completed. If you need additional adjustments I can add formatting rules.

**Comment by matt-cook** [comment]
These are the currently available text formats: http://capital-chaplains.github.io/corpchaps.com/template/ re-open this issue or create a new one if you need more options.
