### ISSUE TITLE
How do I add text under a page title with separate entries beneath it? 

### ISSUE THREAD

**Issue by lisa-rieck** [capital-chaplains/corpchaps.com#19]
So, e.g., on the "Testimonials" page, I'd like to add a line of text at the top (under the heading "Testimonials") that applies to all of the testimonials--something like, "Here’s what clients are saying about Corporate Chaplaincy Consulting."

**Comment by matt-cook** [comment]
I've adjusted it so you can add content the 'main' page for a category (like testimonials) and it will show above the listed content. So this: https://github.com/capital-chaplains/corpchaps.com/edit/gh-pages/testimonials/testimonials.md will look like: http://capital-chaplains.github.io/corpchaps.com/testimonials/
