### ISSUE TITLE
Reduced width problems: main nav dropdown & header image/tagline

### ISSUE THREAD

**Issue by sarahschilling** [capital-chaplains/corpchaps.com#21]
![main nav reduced width](https://cloud.githubusercontent.com/assets/9312364/6205076/3fb346c2-b527-11e4-9352-b915e05d1f14.png)

In Chrome, when I reduce the width of the page, the main nav links disappear (fine), but the button that should result in viewing the nav (I believe as a dropdown) doesn't work for me in Chrome.

And tagline in header image gets cut off...can we discuss what to do about the header image anyway? Maybe temporarily take out the MIchaelangelo image?

**Comment by matt-cook** [comment]
Yes, let's talk about this one Saturday. There's a couple other similar issues with mobile library (generally #3 reference the issue). Once we nail down the layout I'll iron these out.

**Comment by matt-cook** [comment]
blocked by #11, #12, and #13
