### ISSUE TITLE
Changing "About Us" headline in footer

### ISSUE THREAD

**Issue by lisa-rieck** [capital-chaplains/corpchaps.com#24]
We'd like to change "About Us: Wondering Who We Are?" to "Why We Exist." I can't seem to get the new text to show up on the site.

**Comment by matt-cook** [comment]
Made that one tough on you.. it's embedded in an image: https://github.com/capital-chaplains/corpchaps.com/blob/gh-pages/_img/interface/title_about.png

Are you thinking leave the white "About Us" and just change the sub-heading, or replace both?

**Comment by lisa-rieck** [comment]
We'd like to replace both so that the only text that appears there is: Why We Exist

**Comment by matt-cook** [comment]
I've updated this text. Does it still make sense to have Steve's photo? I could remove that and make the mission text larger, which would also solve the problem with #27. @sarahschilling, @lisa-rieck thoughts?

**Comment by sarahschilling** [comment]
I think removing Steve's photo and enlarging the mission text would be fine.

**Comment by matt-cook** [comment]
Will do.
