### ISSUE TITLE
Create About dropdown menu & make 2 pages live

### ISSUE THREAD

**Issue by sarahschilling** [capital-chaplains/corpchaps.com#26]
Please create a dropdown menu for the About section:
- About is no longer a page
- 3 new items under About are:
1. Our Vision (http://capital-chaplains.github.io/corpchaps.com/about/our-vision/)
2. The Need for Corporate Chaplaincy (http://capital-chaplains.github.io/corpchaps.com/about/need-for-corporate-chaplaincy/)
3. The Case for For-Profit Chaplaincy (http://capital-chaplains.github.io/corpchaps.com/about/case-for-for-profit-chaplaincy/)

**Comment by matt-cook** [comment]
Brief instructions for menu edits here: https://github.com/capital-chaplains/corpchaps.com/issues/30#issuecomment-88301685
