### ISSUE TITLE
Remove "Endorsements" section from all but homepage

### ISSUE THREAD

**Issue by sarahschilling** [capital-chaplains/corpchaps.com#27]
Feel free to weigh in on why NOT to do the following, but we feel like it is distracting to have the "Endorsements/Testimonials" section of the footer appear on every page and would prefer it only appear on the homepage.

**Comment by matt-cook** [comment]
Sounds good to me.

**Comment by matt-cook** [comment]
Because of the image overlap from the footer area below it, I'll need to dig up the original design files to update that. Will come back to it.

**Comment by matt-cook** [comment]
Unfortunately, I don't have the original design files for the site.. which make this one tougher.
