### ISSUE TITLE
Get Started URL for Bring Steve to You

### ISSUE THREAD

**Issue by sarahschilling** [capital-chaplains/corpchaps.com#30]
Please change the URL in the dropdown menu to http://capital-chaplains.github.io/corpchaps.com/get-started/bring-steve-to-you/  for Bring Steve to You (it currently points to /private-consultation/

**Comment by matt-cook** [comment]
It's a bit odd, but menus items can be edited here (or the equivalent folder locally): https://github.com/capital-chaplains/corpchaps.com/tree/gh-pages/_data/menu
