### ISSUE TITLE
Create template page with all available font sizes.

### ISSUE THREAD

**Issue by matt-cook** [capital-chaplains/corpchaps.com#33]

**Comment by matt-cook** [comment]
Working example here: http://capital-chaplains.github.io/corpchaps.com/template/

**Comment by sarahschilling** [comment]
Matt,

What do you think about making all of the body text be the same font size as the one you've shown for the block quote?

Sarah

**Comment by matt-cook** [comment]
Sounds good to me. I'm hoping to get through the rest of that cleanup tonight.

**Comment by matt-cook** [comment]
I've updated the text size and h2 formatting: http://capital-chaplains.github.io/corpchaps.com/template/ re-open this issue if you need additional formats (or create a new issue).
