### ISSUE TITLE
Consider Corporate Chaplaincy files ready for store

### ISSUE THREAD

**Issue by sarahschilling** [capital-chaplains/corpchaps.com#38]
Matt,

The 3 docs for the Consider Corporate Chaplaincy package are ready for you now on Dropbox: https://www.dropbox.com/sh/oncfxkhgr40yf7d/AABk5TyN7LTw9dgF0lK5MKVTa?dl=0

Please let me know if that link does NOT give you access for some reason.

Sarah

**Comment by matt-cook** [comment]
Thanks Sarah. I've added this product: https://gumroad.com/products/yUbUg/edit

You'll want to remove the files from Dropbox (or make them private) since these comments are publicly viewable.
