### ISSUE TITLE
Learn More buttons

### ISSUE THREAD

**Issue by sarahschilling** [capital-chaplains/corpchaps.com#40]
Each Learn More button on the Buy Now page can link back to that product's main page, rather than pointing to another page for that product.

Ex. Right now, the Learn More button brings up http://capital-chaplains.github.io/corpchaps.com/store/chaplain/ generated by content in 2015-01-30-chaplain.md. Instead, it can link to http://capital-chaplains.github.io/corpchaps.com/get-started/consider-corporate-chaplaincy/

**Comment by matt-cook** [comment]
I've added a "learn-more" attribute to the product posts so we can specify where those buttons go.
- Is the content of the product posts every shown anywhere? We could just remove that.
- Does the Marketing package have a description page?

**Comment by matt-cook** [comment]
Ah, I see #42 answers that questions!
