### ISSUE TITLE
Buy Now buttons (Issue has Parts A and B)

### ISSUE THREAD

**Issue by sarahschilling** [capital-chaplains/corpchaps.com#41]
PART A
When first clicked, a Buy Now button brings up a popup asking for payment info
![buy now payment info](https://cloud.githubusercontent.com/assets/9312364/6999828/0716e712-dbdb-11e4-9fd3-47ed1f36f3fa.png)

When I click the close (X) button, it switches to the description of what will be purchased and another Buy This button.
![buy now package description](https://cloud.githubusercontent.com/assets/9312364/6999833/22901edc-dbdb-11e4-8427-21425aae7eb9.png)

I would prefer that the description popup with the Buy This button appears first, then the payment info popup.

PART B
The list of documents that appear in the package description popup are incorrect. Where can I change them?

**Comment by matt-cook** [comment]
I've updated part A: https://gumroad.com/
Part B login info was sent in an email
