### ISSUE TITLE
3 blocks on homepage

### ISSUE THREAD

**Issue by lisa-rieck** [capital-chaplains/corpchaps.com#43]
I think we talked about this, but how do we change the text and images and links for the 3 blocks in the middle of the homepage (the ones that link to "The Missing Link," "The Case for For-Profit Chaplaincy," and "The Wheel Is Invented")? I can't find them in the GItHub folders.

**Comment by matt-cook** [comment]
Ah yes, what did we decide to do with those? They need to be edited directly in the homepage layout currently: https://github.com/capital-chaplains/corpchaps.com/blob/gh-pages/_layouts/home.html

Feel free to edit the text and link directly there, or post the update here and I can take care of it for you.
