### ISSUE TITLE
Blog images

### ISSUE THREAD

**Issue by lisa-rieck** [capital-chaplains/corpchaps.com#50]
I tried to load a blog image and couldn't get that to work either. Sorry to be so incompetent with the images! Can you let me know what I need to do differently? Also, is there a way to get the image to also appear on the post page? That could be post-launch, if needed.

I'm also unable to get the "a" to be lowercase in the title of the blog post "Who Needs a Chaplain?"

Also, love the kittens :). I'll delete the test posts before we launch. Thanks!

**Comment by matt-cook** [comment]
I've updated the layout code to pull in the image correctly. It will still break with a space in the filename however, so it would be best to rename the files (perhaps replaces spaces with '-').

Images in the posts are a good idea, let's address that separately.

**Comment by lisa-rieck** [comment]
Sounds good.

**Comment by matt-cook** [comment]
It looks like the 'a' is lowercase: http://capital-chaplains.github.io/corpchaps.com/blog/ were you able to fix it?

**Comment by matt-cook** [comment]
Looks like this was figured out: http://capital-chaplains.github.io/corpchaps.com/blog/
