### ISSUE TITLE
new images for 3 homepage blocks

### ISSUE THREAD

**Issue by sarahschilling** [capital-chaplains/corpchaps.com#56]
Matt,

Could you please let me know the dimensions of the 3 homepage images (currently a dove, a broken chain, and a stone)?

I think it's important to swap in new images for the chain and stone before the relaunch since the current images no longer have anything to do with the text in those blocks.

I'll find images to go there with my remaining Fotolia credits and put them in the Google folder. However, even though I can see where to swap in the new images in the code, I don't know how to create the div id that points to the correct images. So, I will likely need you to insert them once I have the images ready for you.

Thanks, Sarah

**Comment by matt-cook** [comment]
These images are now pulled directly from this folder: https://drive.google.com/open?id=0B-rUPb5gojEtfnVJTlB4UWJ5b3hSbTI3dFFic3J5NnFIVXctbFNqOEE0RGQ3LVNPbFJzcVE&authuser=0 so you can swap with any other 297x297px image.
