### ISSUE TITLE
Main header nav

### ISSUE THREAD

**Issue by sarahschilling** [capital-chaplains/corpchaps.com#6]
Please see the "Things to Fix" Google doc for more details on old and new main header nav.

Desired main header nav is (from left to right, plus dropdowns):

Nav 1: About (corpchaps.com/about)

Nav 2: Get Started (corpchaps.com/get-started ...this doesn't have to be a literal page that can be clicked, because it's the dropdown items that actually matter)
- Dropdown Item 1: Become a Corporate Chaplain (corpchaps.com/get-started/become-a-corporate-chaplain)
- Dropdown Item 2: Start Your Chaplaincy Business (corpchaps.com/get-started/start-your-corporate-chaplaincy-business)
- Dropdown Item 3: Grow Your Chaplaincy Business (corpchaps.com/get-started/grow-your-corporate-chaplaincy-business)
- Dropdown Item 4: Shadow a Chaplain (corpchaps.com/get-started/shadow-a-corporate-chaplain)
- Dropdown Item 5: Bring Steve to You (corpchaps.com/get-started/private-consultation)

Note: I've added "corporate" to the URLs for Dropdown Items 2, 3, and 4, assuming that would be helpful for Google. If not, then the URLs can match the titles.

Nav 3: Blog (corpchaps.com/blog)

Nav 4: Testimonials (corpchaps.com/testimonials)

Nav 5: Contact (corpchaps.com/contact)

Nav 6: Buy Now (corpchaps.com/buy-now)

**Comment by matt-cook** [comment]
I've updated the main nav and URL's. Reorganized a bit: http://capital-chaplains.github.io/corpchaps.com/

I'll go through the Google Doc next and see what I can clean up.
