### ISSUE TITLE
Direct download of docs?

### ISSUE THREAD

**Issue by sarahschilling** [capital-chaplains/corpchaps.com#8]
Matt,

Will the new checkout process enable buyers to immediately download the documents with each package? e.g. Will Steve have to email them the docs after they purchase? Do we even need to offer the option to purchase files on a CD?

**Comment by matt-cook** [comment]
Yes, no need to email docs separately. We're using http://www.gumroad.com so after checkout they'll receive a download page like: ![](https://googledrive.com/host/0B-rUPb5gojEtSTFMU3FPb19yaDA/corpchaps-sale.png)

We'll be using the Overlay method, so it should feel pretty seamless: https://gumroad.com/widgets.

Re. the CD let's check with my dad and see how many people have needed it. Perhaps we could add a "Contact Us if you require the documents on physical media (CD, flash drive, etc.)" link

**Comment by matt-cook** [comment]
You can see this in action now on the "buy now" page: http://capital-chaplains.github.io/corpchaps.com/buy-now/
